In [2]:
print("hello")

hello

In [ ]:
# 파일 입출력

In [ ]:
f = open('name.txt', 'r', encoding='utf-8')
data = f.read()
print(data)
f.close()

토트넘
PSG
바이에른 뮌헨
울버햄튼

In [ ]:
# 입력받아 파일에 쓰기
f = open('name.txt', 'w', encoding='utf-8')
while True:
  team = input('팀: ')
  if not team:
    break
  f.write(team + '\n')
f.close()

In [ ]:
# 엑셀파일 입출력

In [1]:
%pip install pandas openpyxl

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dgsw64/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /Users/dgsw64/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 645.3 kB/s  0:00:18eta 0:00:01
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 1.1 MB/s  0:00:04 eta 0:00:010m
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: numpy, et-xmlfile, pandas, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [openpyxl]3/4 [openpyxl]
Successfully installed et-xmlfile-2.0.0 numpy-2.5.2 openpyxl-3.1.5 pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
df = pd.read_excel('my_grade.xlsx')
add_df = pd.DataFrame([{
  '이름': '조자룡',
  '1차 지필': 63,
  '2차 지필': 75,
  '수행1': 84,
  '수행2': 79,
  '등급': 'C'
}])
modi_file = pd.concat([df, add_df], ignore_index=True)
modi_file.to_excel('new_grede.xlsx', index=False)
modi_file

    이름  1차 지필  2차 지필  수행1  수행2 등급
0   유비     92     88   93   95  A
1   관우     89     90   85   78  B
2   장비     71     84   67   70  V
3  조자룡     63     75   84   79  C

In [ ]:
import pandas as pd
df = pd.read_excel('club.xlsx')
add_df = pd.DataFrame([{
  '학번': 10512,
  '이름': '김하늘',
  '학년': 1,
  '동아리': 'AI연구부',
  '역할': '부원' 
}])
modi_file = pd.concat([df, add_df], ignore_index= True)
modi_file.to_excel('new_club.xlsx', index=True)
modi_file.tail()

      학번   이름  학년     동아리  역할
0  10401  이민호   1  AI 연구부  부장
1  10405  박서연   1  AI 연구부  부원
2  10503  최지우   1  AI 연구부  부원
3  10512  김하늘   1   AI연구부  부원